name: remote ssh command
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.107.0'

    - name: Build
      run: hugo --minify

    - name: Upload build
      uses: actions/upload-artifact@master
      with:
        name: astrotours-devel
        path: public

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.4  
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
                nohup ./astrotours-devel-artifact.sh &
