name: remote ssh command
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ release ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    - name: Build Bootstrap CSS
      run: |
        npm i bootstrap autoprefixer upath sass shelljs
        node src/build-scss.js
    - name: Build
      run: hugo

    - name: Upload build
      uses: actions/upload-artifact@master
      with:
        name: astrotours
        path: public

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.2  
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
                nohup bash -x ./astrotours-artifact.sh </dev/null &>/dev/null &
